### ISSUE TITLE
More info Dialog opens verrryy slowly and Dashboard hangs 

### ISSUE THREAD

**Issue by thundergreen** [JurajNyiri/PlexMeetsHomeAssistant#58]
**Describe the bug**

When I visit my dashboard page with the card (in a swipe card embedded) my dashboard hangs like hell and more info dialog opens only after a large amount of time
**To Reproduce**
1. Go to 'plex card'
2. Click on '.desired Movie
3. More info dialog opens after a huge delay

**Expected behavior**
I expect to open the dialogue fast

**Screenshots**
![image](https://user-images.githubusercontent.com/13320319/140655142-748cff5d-cef9-42a6-b389-f3574db70143.png)

clicking on a movie (Caroline)...

does not open the more info page :(  Same for Music and Series.

If this is a network error, please open network tab in your browser developer tools and paste in as much information as possible about the failing request. This will make it a lot easier to help you as soon as possible.

**Checks**
Please check below if true:

[x ] I am running Home Assistant on HTTP protocol
[ ] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[ ] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[ x] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
Copy and paste your card configuration. Make sure to hide token and other sensitive information.
```
- type: custom:swipe-card
  card_width: "1160px"
  parameters:
    effect: "coverflow"
    grabCursor: true
    centeredSlides: true
    slidesPerView: "auto"
    coverflowEffect:
      rotate: 50
      stretch: 0
      depth: 100
      modifier: 1
      slideShadows: true
    pagination:
      type: "bullets"
  cards:
    - type: custom:plex-meets-homeassistant
      protocol: https
      sort: lastViewedAt:desc
      playTrailer: true
      showExtras: true
      showSearch: false
      ip: plex-movies.ddns.net
      token: 2r84cSrejeZjyEK9r4Kf
      port: "443"
      entity:
        - kodi | media_player.libreelec
      libraryName: Movies
      maxCount: ""
      maxRows: "3"
      useHorizontalScroll: "No"
      displayTitleMain: "Yes"
      displaySubtitleMain: "Yes"
      minWidth: "130"
      minEpisodeWidth: ""
      minExpandedWidth: ""
      fontSize1: ""
      fontSize2: ""
      fontSize3: ""
      fontSize4: ""
      minExpandedHeight: ""
      title: Last played ...

    - type: custom:plex-meets-homeassistant
      protocol: https
      sort: addedAt:desc
      playTrailer: true
      showExtras: true
      showSearch: false
      ip: plex-movies.ddns.net
      token: 2r84cSrejeZjyEK9r4Kf
      port: "443"
      entity:
        - kodi | media_player.libreelec
      libraryName: Movies
      maxCount: "16"
      maxRows: ""
      useHorizontalScroll: "No"
      displayTitleMain: "Yes"
      displaySubtitleMain: "Yes"
      minWidth: "130"
      minEpisodeWidth: ""
      minExpandedWidth: ""
      fontSize1: ""
      fontSize2: ""
      fontSize3: ""
      fontSize4: ""
      minExpandedHeight: ""
      title: Last added ...

    - type: custom:plex-meets-homeassistant
      protocol: https
      sort: addedAt:desc
      playTrailer: true
      showExtras: true
      showSearch: false
      ip: plex-movies.ddns.net
      token: 2r84cSrejeZjyEK9r4Kf
      port: "443"
      entity:
        - kodi | media_player.libreelec
      libraryName: TV Shows
      maxCount: ""
      maxRows: "4"
      useHorizontalScroll: "No"
      displayTitleMain: "Yes"
      displaySubtitleMain: "Yes"
      minWidth: "200"
      minEpisodeWidth: "1"
      minExpandedWidth: "235"
      fontSize1: "10"
      fontSize2: "12"
      fontSize3: "15"
      fontSize4: "10"
      minExpandedHeight: "150"
      title: TV Shows

    - type: custom:plex-meets-homeassistant
      protocol: https
      sort: titleSort:asc
      displayType: "8"
      playTrailer: false
      showExtras: true
      showSearch: false
      ip: plex-movies.ddns.net
      token: qYk2eDhd7MLH1shuyzz4
      port: "443"
      entity:
        - kodi | media_player.libreelec
      libraryName: Music
      maxCount: ""
      maxRows: "10"
      useHorizontalScroll: "No"
      displayTitleMain: "Yes"
      displaySubtitleMain: "Yes"
      minWidth: "130"
      minEpisodeWidth: ""
      minExpandedWidth: ""
      fontSize1: ""
      fontSize2: ""
      fontSize3: ""
      fontSize4: ""
      minExpandedHeight: ""
      title: "Music"
```
**Card Version**
Replace this text with version of card you are using.

**Plex Version**
Replace this text with version of Plex you are using.

**Additional context**
