### ISSUE TITLE
Bug: Card freezes when clicking on movie (Desktop)

### ISSUE THREAD

**Issue by NachtaktiverHalbaffe** [JurajNyiri/PlexMeetsHomeAssistant#68]
**Describe the bug**
On desktop when I click on a movie on the plex card, it wont play the animation and the whole web ui of HA freezes until a complete page refresh. Only happens on Fullscreen desktop (exception: shrinked the windowsize down to a phone-like aspect ratio). On mobile and everything else it works fine. The console is throwing some violation warnings (see screenshot below). 

This also appears when opening the editor for the card, this time across all plattforms. In this case, it does take a long time to load, but wont freeze completly.

**To Reproduce**
1. Open tab with the plex card inside
2. Click on any movie

**Expected behavior**
Open the movie with an smooth transition, No freeze ups

**Screenshots**
My freezed up screen. Wanted to open the top left movie
![1](https://user-images.githubusercontent.com/57433516/148247714-bdb67200-f70c-44f6-b6c2-3667213b6230.jpg)
Console logs
![2](https://user-images.githubusercontent.com/57433516/148247893-e8794986-b7ff-433f-89ad-471738195b22.jpg)

**Checks**
Please check below if true:

[x] I am running Home Assistant on HTTP protocol
[ ] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[x] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[ ] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
````yaml
type: custom:plex-meets-homeassistant
token: XXXXXXXXXX
ip: 192.168.XXX.XX
port: 'XXXXXXXXXXX'
libraryName: Filme
protocol: http
maxCount: '24'
sort: audienceRating:desc
playTrailer: true
showExtras: true
showSearch: true
runBefore: script.plex_schauen
entity:
  - plexPlayer | LG 49UJ635V-ZF | 192.168.XXX.XX | XXXXXXXXXXXX
  - cast | media_player.XXXX
title: Filme
maxRows: ''
useHorizontalScroll: 'No'
displayTitleMain: 'Yes'
displaySubtitleMain: 'Yes'
minWidth: ''
minEpisodeWidth: ''
minExpandedWidth: ''
fontSize1: ''
fontSize2: ''
fontSize3: ''
fontSize4: ''
minExpandedHeight: ''
displayType: ''
useShuffle: 'No'
````

**Card Version**
3.4.1

**Plex Version**
1.24.5.5173 (Via offical Truenas Core Plex plugin)

**Additional context**
---
