### ISSUE TITLE
Details flow over home assistant header

### ISSUE THREAD

**Issue by m7r** [JurajNyiri/PlexMeetsHomeAssistant#97]
**Describe the bug**
Track view parts scroll over the home assistant header.

**To Reproduce**
1. Open Album details
2. Scroll to the bottom
3. Some elements are over the header

**Expected behavior**
The hole card content should be under the header

**Screenshots**
<img width="1150" alt="image" src="https://github.com/JurajNyiri/PlexMeetsHomeAssistant/assets/4331597/e2e7c8fa-d945-440c-8488-ef804063601a">

**Checks**
[ ] I am running Home Assistant on HTTP protocol
[x] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[x] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[x] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
```yaml
type: custom:plex-meets-homeassistant
protocol: https
ip: plex.malamaglo.de
token: [REMOVED]
port: '443'
sort: titleSort:asc
showSearch: true
entity:
  - sonos | media_player.sonos_esszimmer
libraryName: Musik
useHorizontalScroll: 'No'
useShuffle: 'No'
displayTitleMain: 'Yes'
displaySubtitleMain: 'Yes'
displayType: '9'
```
**Card Version**
3.6.7

**Plex Version**
1.32.4.7195

**Device information**
iOS 16.5.1 Safari & Homeassistant App
macOS 13.4.1 Safari & Chrome
