### ISSUE TITLE
Search in Safari only character by character

### ISSUE THREAD

**Issue by m7r** [JurajNyiri/PlexMeetsHomeAssistant#98]
**Describe the bug**
The hole card gets reloaded after entering a key in the search field.

**To Reproduce**
1. In Safari macOS or iOS enter a character into the search field
2. After first key the card will reload and search field lost focus
3. Repeat on 1.

**Expected behavior**
As in Chrome the search field should be stay active and I can type in the hole search term

**Screenshots**
--

**Checks**
[ ] I am running Home Assistant on HTTP protocol
[x] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[x] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.
[x] My Plex server is running on HTTPS and has a valid certificate.

**Card Configuration**
```yaml
type: custom:plex-meets-homeassistant
protocol: https
ip: plex.malamaglo.de
token: [REMOVED]
port: '443'
sort: titleSort:asc
showSearch: true
entity:
  - sonos | media_player.sonos_esszimmer
libraryName: Musik
useHorizontalScroll: 'No'
useShuffle: 'No'
displayTitleMain: 'Yes'
displaySubtitleMain: 'Yes'
displayType: '9'
```
**Card Version**
3.6.7

**Plex Version**
1.32.4.7195

**Device information**
iOS 16.5.1 Safari & Homeassistant App
macOS 13.4.1 Safari
